import 'package:indomgram/models/user_model.dart';
import 'package:indomgram/models/post_model.dart';
import 'package:indomgram/models/reel_model.dart';
import 'package:indomgram/models/message_model.dart';

class DummyData {
  // Users
  static final User currentUser = User(
    id: 'current_user',
    username: 'indiancoder',
    name: 'Indian Developer',
    profileImageUrl: 'https://picsum.photos/id/1012/300',
    bio: 'Flutter Developer | Coffee Enthusiast | Tech Lover',
    posts: 42,
    followers: 1024,
    following: 256,
    isVerified: true,
  );

  static final List<User> users = [
    currentUser,
    User(
      id: 'user1',
      username: 'techindian',
      name: 'Tech Indian',
      profileImageUrl: 'https://picsum.photos/id/1025/300',
      bio: 'Digital Creator | Tech Enthusiast',
      posts: 120,
      followers: 10500,
      following: 350,
      isVerified: true,
    ),
    User(
      id: 'user2',
      username: 'indianartist',
      name: 'Indian Artist',
      profileImageUrl: 'https://picsum.photos/id/1027/300',
      bio: 'Artist | Creator | Dreamer',
      posts: 78,
      followers: 5200,
      following: 420,
    ),
    User(
      id: 'user3',
      username: 'traveller_indian',
      name: 'Indian Traveller',
      profileImageUrl: 'https://picsum.photos/id/1035/300',
      bio: 'Travel | Adventure | Photography',
      posts: 215,
      followers: 15800,
      following: 195,
      isVerified: true,
    ),
    User(
      id: 'user4',
      username: 'foodie_india',
      name: 'Indian Foodie',
      profileImageUrl: 'https://picsum.photos/id/1062/300',
      bio: 'Food Blogger | Chef | Recipe Creator',
      posts: 89,
      followers: 7500,
      following: 312,
    ),
  ];

  // Posts
  static final List<Post> posts = [
    Post(
      id: 'post1',
      user: users[0],
      imageUrl: 'https://picsum.photos/id/100/800/800',
      caption: 'Coding session in progress! #flutter #dart #programming',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      likes: 256,
      comments: 42,
      hashtags: ['flutter', 'dart', 'programming', 'developer'],
      location: 'Mumbai, India',
    ),
    Post(
      id: 'post2',
      user: users[1],
      imageUrl: 'https://picsum.photos/id/1025/800/800',
      caption: 'Enjoying the beautiful sunset at the beach! #sunset #beach #vibes',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      likes: 1024,
      comments: 128,
      hashtags: ['sunset', 'beach', 'vibes', 'nature'],
      location: 'Goa, India',
    ),
    Post(
      id: 'post3',
      user: users[2],
      imageUrl: 'https://picsum.photos/id/1059/800/800',
      caption: 'New art piece finished today. What do you think? #art #creative',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
      likes: 512,
      comments: 78,
      hashtags: ['art', 'creative', 'painting', 'artist'],
    ),
    Post(
      id: 'post4',
      user: users[3],
      imageUrl: 'https://picsum.photos/id/1080/800/800',
      caption: 'Exploring the mountains this weekend! #travel #adventure',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      likes: 768,
      comments: 93,
      hashtags: ['travel', 'adventure', 'mountains', 'nature'],
      location: 'Himalayas, India',
    ),
    Post(
      id: 'post5',
      user: users[4],
      imageUrl: 'https://picsum.photos/id/102/800/800',
      caption: 'Homemade butter chicken recipe! Check out my blog for more. #food #recipe',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      likes: 423,
      comments: 56,
      hashtags: ['food', 'recipe', 'cooking', 'indianfood'],
      location: 'Delhi, India',
    ),
  ];

  // Reels
  static final List<Reel> reels = [
    Reel(
      id: 'reel1',
      user: users[0],
      videoUrl: 'https://example.com/reel1.mp4',
      thumbnailUrl: 'https://picsum.photos/id/1039/800/1200',
      caption: 'Check out this quick Flutter tutorial! #flutter #coding',
      audio: 'Original Audio - indiancoder',
      likes: 2048,
      comments: 305,
      shares: 127,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Reel(
      id: 'reel2',
      user: users[1],
      videoUrl: 'https://example.com/reel2.mp4',
      thumbnailUrl: 'https://picsum.photos/id/1043/800/1200',
      caption: 'Latest tech review! #tech #gadgets',
      audio: 'Trending Sound - TechReviews',
      likes: 1536,
      comments: 215,
      shares: 95,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Reel(
      id: 'reel3',
      user: users[2],
      videoUrl: 'https://example.com/reel3.mp4',
      thumbnailUrl: 'https://picsum.photos/id/1047/800/1200',
      caption: 'Timelapse of my latest artwork! #art #creative',
      audio: 'Relaxing Music - ArtistVibes',
      likes: 3072,
      comments: 428,
      shares: 256,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    Reel(
      id: 'reel4',
      user: users[3],
      videoUrl: 'https://example.com/reel4.mp4',
      thumbnailUrl: 'https://picsum.photos/id/1051/800/1200',
      caption: 'Mountain climbing adventure! #travel #adventure',
      audio: 'Adventure - NatureSound',
      likes: 4096,
      comments: 512,
      shares: 384,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    Reel(
      id: 'reel5',
      user: users[4],
      videoUrl: 'https://example.com/reel5.mp4',
      thumbnailUrl: 'https://picsum.photos/id/1062/800/1200',
      caption: '30-second easy recipe! #food #cooking',
      audio: 'Cooking Sounds - FoodieChannel',
      likes: 1280,
      comments: 192,
      shares: 104,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
  ];

  // Messages
  static final List<Conversation> conversations = [
    Conversation(
      id: 'conv1',
      user: users[1],
      messages: [
        Message(
          id: 'msg1',
          sender: users[1],
          content: 'Hey, how are you?',
          timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
          isRead: true,
        ),
        Message(
          id: 'msg2',
          sender: currentUser,
          content: 'I\'m good! Working on a new Flutter project.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 25)),
          isRead: true,
        ),
        Message(
          id: 'msg3',
          sender: users[1],
          content: 'That sounds exciting! Can you share more details?',
          timestamp: DateTime.now().subtract(const Duration(minutes: 20)),
          isRead: true,
        ),
        Message(
          id: 'msg4',
          sender: currentUser,
          content: 'It\'s a social media app similar to Instagram. I\'m using Flutter and Firebase.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
          isRead: true,
        ),
        Message(
          id: 'msg5',
          sender: users[1],
          content: 'Nice! Let me know if you need any help with testing.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 10)),
          isRead: false,
        ),
      ],
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 10)),
      unread: true,
    ),
    Conversation(
      id: 'conv2',
      user: users[2],
      messages: [
        Message(
          id: 'msg6',
          sender: currentUser,
          content: 'I loved your latest artwork!',
          timestamp: DateTime.now().subtract(const Duration(hours: 2)),
          isRead: true,
        ),
        Message(
          id: 'msg7',
          sender: users[2],
          content: 'Thank you so much! It took me about 3 days to complete.',
          timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 55)),
          isRead: true,
        ),
        Message(
          id: 'msg8',
          sender: currentUser,
          content: 'The details are amazing. What medium did you use?',
          timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 50)),
          isRead: true,
        ),
        Message(
          id: 'msg9',
          sender: users[2],
          content: 'It\'s acrylic on canvas. I\'m planning to do a tutorial soon!',
          timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 45)),
          isRead: true,
        ),
      ],
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 1, minutes: 45)),
      unread: false,
    ),
    Conversation(
      id: 'conv3',
      user: users[3],
      messages: [
        Message(
          id: 'msg10',
          sender: users[3],
          content: 'Where did you take that amazing mountain photo?',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
          isRead: true,
        ),
        Message(
          id: 'msg11',
          sender: currentUser,
          content: 'It was in Himachal Pradesh, near Manali. Have you been there?',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
          isRead: true,
        ),
        Message(
          id: 'msg12',
          sender: users[3],
          content: 'Not yet, but it\'s on my bucket list! Any recommendations for stays?',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
          isRead: false,
        ),
      ],
      lastMessageTime: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      unread: true,
    ),
    Conversation(
      id: 'conv4',
      user: users[4],
      messages: [
        Message(
          id: 'msg13',
          sender: currentUser,
          content: 'Your butter chicken recipe was delicious! My family loved it.',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
          isRead: true,
        ),
        Message(
          id: 'msg14',
          sender: users[4],
          content: 'I\'m so glad to hear that! Did you make any modifications?',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 4)),
          isRead: true,
        ),
        Message(
          id: 'msg15',
          sender: currentUser,
          content: 'I added a bit more cream and reduced the spice level slightly.',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
          isRead: true,
        ),
        Message(
          id: 'msg16',
          sender: users[4],
          content: 'That sounds perfect! I\'ll share my naan recipe next week.',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
          isRead: true,
        ),
      ],
      lastMessageTime: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
      unread: false,
    ),
  ];

  // User Grid Posts
  static final List<String> userGridPosts = [
    'https://picsum.photos/id/100/300/300',
    'https://picsum.photos/id/1001/300/300',
    'https://picsum.photos/id/1002/300/300',
    'https://picsum.photos/id/1003/300/300',
    'https://picsum.photos/id/1004/300/300',
    'https://picsum.photos/id/1005/300/300',
    'https://picsum.photos/id/1006/300/300',
    'https://picsum.photos/id/1008/300/300',
    'https://picsum.photos/id/1009/300/300',
    'https://picsum.photos/id/101/300/300',
    'https://picsum.photos/id/1010/300/300',
    'https://picsum.photos/id/1011/300/300',
    'https://picsum.photos/id/1012/300/300',
    'https://picsum.photos/id/1013/300/300',
    'https://picsum.photos/id/1014/300/300',
    'https://picsum.photos/id/1015/300/300',
  ];

  // Search Explore Posts
  static final List<String> explorePosts = [
    'https://picsum.photos/id/1018/500/500',
    'https://picsum.photos/id/1019/800/500',
    'https://picsum.photos/id/1020/500/800',
    'https://picsum.photos/id/1021/500/500',
    'https://picsum.photos/id/1022/800/500',
    'https://picsum.photos/id/1023/500/800',
    'https://picsum.photos/id/1024/500/500',
    'https://picsum.photos/id/1025/800/500',
    'https://picsum.photos/id/1026/500/800',
    'https://picsum.photos/id/1027/500/500',
    'https://picsum.photos/id/1028/800/500',
    'https://picsum.photos/id/1029/500/800',
    'https://picsum.photos/id/1030/500/500',
    'https://picsum.photos/id/1031/800/500',
    'https://picsum.photos/id/1032/500/800',
    'https://picsum.photos/id/1033/500/500',
    'https://picsum.photos/id/1034/800/500',
    'https://picsum.photos/id/1035/500/800',
    'https://picsum.photos/id/1036/500/500',
    'https://picsum.photos/id/1037/800/500',
    'https://picsum.photos/id/1038/500/800',
  ];
}
